version: "3.4"

services:
  backend:
    build:
      dockerfile: .Dockerfile.development
      context: ./projects/webapi
    volumes:
      - /app/node_modules
      - ./projects/webapi:/app
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=clocked
      - MONGO_URI